custom_range_based_loop: custom_range_based_loop.o
	g++ custom_range_based_loop.o -o custom_range_based_loop

custom_range_based_loop.o: custom_range_based_loop.cpp
	g++ -std=c++11 custom_range_based_loop.cpp -o custom_range_based_loop.o -c -g

