iterate_unique_ptr: iterate_unique_ptr.o
	g++ iterate_unique_ptr.o -o iterate_unique_ptr

iterate_unique_ptr.o: iterate_unique_ptr.cpp
	g++ -std=c++14 iterate_unique_ptr.cpp -o iterate_unique_ptr.o -c -g

